name: Setup UI Env

on:
  workflow_call:
    inputs:
      config-path:
        TODO: RC remove
        type: string
    secrets:
      token:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install Python for node-sass
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends python2

      - name: Install packages
        run: ./scripts/bootstrap
