name: Build (Release)
on:
  push:
    tags:
      # TODO: RC
      - richard-drone-ui-v*
env:
  ENVIRONMENT: production

jobs:
  # test:
  #   uses: ./.github/workflows/test.yaml
  build-and-upload:
    uses: ./.github/workflows/build-and-upload.yaml
    # needs: test
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      CI_BUILD_TAG: ${{github.ref_name}}
