name: Build and Upload

on:
  workflow_call:
    inputs:
      CI_BRANCH:
        required: false
        type: string
      CI_BUILD_TAG:
        required: false
        type: string

env:
  CI_BRANCH: ${{inputs.CI_BRANCH || ''}}
  CI_BUILD_TAG: ${{inputs.CI_BUILD_TAG || ''}}

jobs:
  build:
    runs-on: ubuntu-latest
    # needs: [set-envs, test]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run Setup
        uses: ./.github/actions/setup

      - id: build
        name: Build
        # -l -v latest2
        run: ./scripts/build-static

      - name: Stash build
        uses: actions/upload-artifact@v4
        with:
          name: BUILD_DIR
          path: ${{ steps.build.outputs.BUILD_DIR }}
          retention-days: 1

      - name: Stash Archive
        if: ${{ env.CI_BUILD_TAG != ''}}
        uses: actions/upload-artifact@v4
        with:
          name: BUILD_TGZ
          path: ${{ steps.build.outputs.BUILD_TGZ }}
          retention-days: 1
  # upload:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'
  #   env:
  #     GS_BUCKET_NAME:
  #   steps:
  #     - name: Download build directory
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: BUILD_DIR
  #         path: build_dir
  #     - name: Download build tar
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: BUILD_TGZ
  #         path: build_tgz
  #     # https://github.com/google-github-actions/auth
  #     - name: auth
  #       uses: 'google-github-actions/auth@v2'
  #       with:
  #         credentials_json: ''
  #         # workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
  #         # service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
  #     # https://github.com/google-github-actions/upload-cloud-storage
  #     - name: upload build
  #       uses: 'google-github-actions/upload-cloud-storage@v2'
  #       with:
  #         path: build_dir
  #         # https://releases.rancher.com/ui/2.8.0/...
  #         destination: releases.rancher.com/ui/${{ env.VERSION }}
  #         parent: false
  #         headers: |-
  #           cache-control: no-cache,must-revalidate
  #     - name: upload tar
  #       uses: 'google-github-actions/upload-cloud-storage@v2'
  #       with:
  #         path: build_tgz
  #         # https://releases.rancher.com/ui/2.8.0.tar.gz
  #         destination: releases.rancher.com/ui
  #         parent: false

#project_id
# GS_PROJECT_NAME 'Rancher'
# VERSION
# CDN="releases.rancher.com/ui"
# GS_URL="${GS_URL:-gs://${CDN}}"
# https://releases.rancher.com/ui/latest2/index.html


# https://stackoverflow.com/questions/59874409/trigger-github-workflow-only-if-pushed-to-specific-branch-and-tag-exists
