name: Tests
on:
  push:
    branches:
      - release-2.7
  pull_request:
    branches:
      - release-2.7
  # This tells GH that the workflow is reusable
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run Setup
        uses: ./.github/actions/setup

      - name: Run linter
        run: yarn lint:js
